version: 2
updates:
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'flutter'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:15'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'ci'
